# Generated by Django 3.0 on 2022-04-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('slot_time', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.User')),
            ],
        ),
    ]
