# Generated by Django 3.2.12 on 2022-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_type', models.TextField(default='General Admission')),
                ('price', models.IntegerField(default=0)),
                ('match_date', models.TextField(default='XX/XX/XX')),
            ],
        ),
    ]
