# Generated by Django 3.2.12 on 2022-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('slot_time', models.TextField()),
            ],
        ),
    ]
