# Generated by Django 3.2.12 on 2022-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(default='XX/XX/XX')),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='match_date',
        ),
    ]
