# Generated by Django 3.2.12 on 2022-03-29 18:11

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20220329_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(default=system.models.default_match, on_delete=django.db.models.deletion.CASCADE, to='system.match'),
        ),
    ]
