# Generated by Django 3.0.5 on 2022-04-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20220402_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(default='XX/XX/XX')),
                ('time', models.TextField(default='XX:XX')),
                ('team1', models.TextField(default='')),
                ('team2', models.TextField(default='')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('location', models.TextField(default='')),
            ],
        ),
    ]
