# Generated by Django 3.0 on 2022-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanTierFee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fan_tier', models.TextField()),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
    ]
