# Generated by Django 3.0 on 2022-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_fantierfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='transaction_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
