# Generated by Django 3.2.12 on 2022-03-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='type',
            new_name='ticket_type',
        ),
    ]
