# Generated by Django 3.0 on 2022-04-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_player_playersalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fan_tier', models.TextField()),
                ('role', models.TextField()),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='salary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Salary'),
        ),
        migrations.DeleteModel(
            name='PlayerSalary',
        ),
    ]
