# Generated by Django 3.0 on 2022-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20220402_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.TextField(default='fan')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fan_tier', models.TextField(default='fan')),
            ],
        ),
    ]
