# Generated by Django 3.0 on 2022-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_role_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.TextField(default='fan')),
                ('path', models.TextField(default='/')),
            ],
        ),
    ]
