# Generated by Django 3.0 on 2022-04-03 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.sql.query
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20220403_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(limit_choices_to={django.db.models.sql.query.Query(system.models.User)}, on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
    ]
