# Generated by Django 3.0 on 2022-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20220403_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='salary',
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(related_name='players', to='system.Match'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
        migrations.CreateModel(
            name='MatchPlayerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_shots', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('attempted_passes', models.IntegerField(default=0)),
                ('made_passes', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Player')),
            ],
        ),
    ]
