# Generated by Django 3.0 on 2022-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20220404_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.TextField(choices=[('Attacker', 'Attacker'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], default='Midfielder'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.TextField(choices=[('Injured', 'Injured'), ('Ready to play', 'Ready to play'), ('Unknown', 'Unknown')], default='Ready to play'),
        ),
    ]
