# Generated by Django 3.0 on 2022-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_auto_20220410_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(related_name='players', through='system.MatchPlayerDetails', to='system.Match'),
        ),
    ]
