# Generated by Django 3.0 on 2022-04-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_player_matches'),
        ('system', '0021_auto_20220410_2217'),
    ]

    operations = [
    ]
