# Generated by Django 3.0 on 2022-04-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20220412_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('role__in', ['player']), ('player__isnull', True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
    ]
