# Generated by Django 3.0.5 on 2022-04-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20220412_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('role__in', ['player']), ('player__isnull', True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
    ]
