# Generated by Django 3.0 on 2022-04-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_ticketuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='system.User'),
        ),
    ]
