# Generated by Django 3.0 on 2022-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20220417_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/', verbose_name='Image'),
        ),
    ]
