# Generated by Django 3.0.5 on 2022-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20220417_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
