# Generated by Django 3.0 on 2022-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20220417_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/', verbose_name='Image'),
        ),
    ]
