# Generated by Django 3.0 on 2022-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Image'),
        ),
    ]
