# Generated by Django 3.0 on 2022-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_auto_20220417_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayerdetails',
            name='attempted_tackles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayerdetails',
            name='made_tackles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayerdetails',
            name='shots_on_target',
            field=models.IntegerField(default=0),
        ),
    ]
